// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "gcsystemmsgs.proto" (syntax proto2)
// tslint:disable
/**
 * @generated from protobuf enum ESOMsg
 */
export enum ESOMsg {
    /**
     * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
     */
    UNSPECIFIED$ = 0,
    /**
     * @generated from protobuf enum value: k_ESOMsg_Create = 21;
     */
    k_ESOMsg_Create = 21,
    /**
     * @generated from protobuf enum value: k_ESOMsg_Update = 22;
     */
    k_ESOMsg_Update = 22,
    /**
     * @generated from protobuf enum value: k_ESOMsg_Destroy = 23;
     */
    k_ESOMsg_Destroy = 23,
    /**
     * @generated from protobuf enum value: k_ESOMsg_CacheSubscribed = 24;
     */
    k_ESOMsg_CacheSubscribed = 24,
    /**
     * @generated from protobuf enum value: k_ESOMsg_CacheUnsubscribed = 25;
     */
    k_ESOMsg_CacheUnsubscribed = 25,
    /**
     * @generated from protobuf enum value: k_ESOMsg_UpdateMultiple = 26;
     */
    k_ESOMsg_UpdateMultiple = 26,
    /**
     * @generated from protobuf enum value: k_ESOMsg_CacheSubscriptionRefresh = 28;
     */
    k_ESOMsg_CacheSubscriptionRefresh = 28,
    /**
     * @generated from protobuf enum value: k_ESOMsg_CacheSubscribedUpToDate = 29;
     */
    k_ESOMsg_CacheSubscribedUpToDate = 29
}
/**
 * @generated from protobuf enum EGCBaseClientMsg
 */
export enum EGCBaseClientMsg {
    /**
     * @generated synthetic value - protobuf-ts requires all enums to have a 0 value
     */
    UNSPECIFIED$ = 0,
    /**
     * @generated from protobuf enum value: k_EMsgGCPingRequest = 3001;
     */
    k_EMsgGCPingRequest = 3001,
    /**
     * @generated from protobuf enum value: k_EMsgGCPingResponse = 3002;
     */
    k_EMsgGCPingResponse = 3002,
    /**
     * @generated from protobuf enum value: k_EMsgGCToClientPollConvarRequest = 3003;
     */
    k_EMsgGCToClientPollConvarRequest = 3003,
    /**
     * @generated from protobuf enum value: k_EMsgGCToClientPollConvarResponse = 3004;
     */
    k_EMsgGCToClientPollConvarResponse = 3004,
    /**
     * @generated from protobuf enum value: k_EMsgGCCompressedMsgToClient = 3005;
     */
    k_EMsgGCCompressedMsgToClient = 3005,
    /**
     * @generated from protobuf enum value: k_EMsgGCCompressedMsgToClient_Legacy = 523;
     */
    k_EMsgGCCompressedMsgToClient_Legacy = 523,
    /**
     * @generated from protobuf enum value: k_EMsgGCToClientRequestDropped = 3006;
     */
    k_EMsgGCToClientRequestDropped = 3006,
    /**
     * @generated from protobuf enum value: k_EMsgGCClientWelcome = 4004;
     */
    k_EMsgGCClientWelcome = 4004,
    /**
     * @generated from protobuf enum value: k_EMsgGCServerWelcome = 4005;
     */
    k_EMsgGCServerWelcome = 4005,
    /**
     * @generated from protobuf enum value: k_EMsgGCClientHello = 4006;
     */
    k_EMsgGCClientHello = 4006,
    /**
     * @generated from protobuf enum value: k_EMsgGCServerHello = 4007;
     */
    k_EMsgGCServerHello = 4007,
    /**
     * @generated from protobuf enum value: k_EMsgGCClientConnectionStatus = 4009;
     */
    k_EMsgGCClientConnectionStatus = 4009,
    /**
     * @generated from protobuf enum value: k_EMsgGCServerConnectionStatus = 4010;
     */
    k_EMsgGCServerConnectionStatus = 4010
}
