// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "steammessages_unified_base.steamworkssdk.proto" (syntax proto2)
// tslint:disable
/**
 * @generated from protobuf enum EProtoExecutionSite
 */
export enum EProtoExecutionSite {
    /**
     * @generated from protobuf enum value: k_EProtoExecutionSiteUnknown = 0;
     */
    k_EProtoExecutionSiteUnknown = 0,
    /**
     * @generated from protobuf enum value: k_EProtoExecutionSiteSteamClient = 3;
     */
    k_EProtoExecutionSiteSteamClient = 3
}
